version: "3.8"
services:
  fundi_app:
    container_name: jenzi_fundi_service
    build: .
    restart: always
    ports:
      - "27800:27800"
    networks:
      - pc-local
    environment:
      - DB_USERNAME=jenzi
      - DB_PASSWORD=jenzi@2022
      - DB_HOST=mysqli
      - EXEC_ENV=prod
      - DB_NAME=jenzi
      - EUREKA_URI=http://eureka-server:8761/eureka
      - REDIS_PORT=6379
      - REDIS_HOST=redis-server
      - MQ_HOST=mq



networks:
  pc-local:
    external: true