spring:
  main:
    banner-mode: off
    log-startup-info: false

  profiles:
    active: ${EXEC_ENV:prod}
  application:
    name: fundi-service
  webflux:
    base-path: /fundi/api

#
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


server:
  port: 27800
