spring:
  main:
    banner-mode: off
    log-startup-info: false
    allow-bean-definition-overriding: true

  profiles:
    active: ${EXEC_ENV:prod}
  application:
    name: fundi-service
  webflux:
    base-path: /fundi/api
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USER:guest}
    password: ${MQ_PASSWORD:guest}

#
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: false



app:
  params:
    redis:
      port: ${REDIS_PORT:6380}
      host: ${REDIS_HOST:localhost}
    variables:
      location_key: jenzi:locations
      locator_delay: 10000
server:
  port: 27800
