spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:jenzi_app}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ ${DB_NAME:jenzi_app}
    password: ${DB_PASSWORD:jenziapp}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
