spring:
  main:
    banner-mode: off
    log-startup-info: false

  profiles:
    active: ${ENV:test}
  application:
    name: fundi-service

#
eureka:
  client:
    enabled: false

server:
  port: 27800
  servlet:
    context-path: /fundi/api