spring:
  main:
    banner-mode: off
    log-startup-info: false

  profiles:
    active: ${EXEC_ENV:dev}
  application:
    name: fundi-service
  webflux:
    base-path: /fundi/api

#
eureka:
  client:
    enabled: false

server:
  port: 27800
