spring:
  main:
    banner-mode: off
    log-startup-info: false

  profiles:
    active: ${EXEC_ENV:prod}
  application:
    name: fundi-service
  webflux:
    base-path: /fundi/api

#
eureka:
  client:
    service-url:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

app:
  params:
    redis:
      port: ${REDIS_PORT:6380}
      host: ${REDIS_HOST:localhost}
    variables:
      location_key: jenzi:locations
      locator_delay: 10000
server:
  port: 27800
